# General Jekyll Config
url: http://cecilialee.github.io/
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock]

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Jekyll SEO Tag plugin
title: Data Science Journal
description: A Data Science Journal by Cecilia Lee.
author: Cecilia Lee

twitter:
  username: cecilialeehs