baseURL = "https://github.com/cecilialee/cecilialee.github.io"
languageCode = "en-us"
title = "Cecilia Lee"
theme = "hugo-theme-cactus-plus"
publishDir = "docs"

[params]
	name = "Cecilia Lee"
	description = "A Data Science Journal"
	bio = "A Data Science Journal"